# vi: expandtab shiftwidth=2 softtabstop=2

- termination: http
  connections: 200
  samples: 2
  duration: 3m
  path: /1024.html
  concurrency: 18
  tool: wrk
  serverReplicas: 45
  requestTimeout: 10s
  delay: 10s

- termination: edge
  connections: 200
  samples: 2
  duration: 3m
  path: /1024.html
  concurrency: 18
  tool: wrk
  serverReplicas: 45
  requestTimeout: 10s
  delay: 10s

